set columns=82
set guioptions-=T " remove toolbar
set guioptions-=r " remove right scrollbar
set guioptions-=l " remove left scrollbar

if has('gui_running')
  " Make shift-insert work like in Xterm
  map  <S-Insert> <MiddleMouse>
  map! <S-Insert> <MiddleMouse>
endif
