
"
" Basic editor settings
"
    set t_Co=256

    syntax on
    colorscheme wombat256mod

    filetype plugin indent on

    set autoindent
    set backspace=indent,eol,start
    set complete-=i
    set cursorline
    set expandtab
    set hidden
    set hls
    set ignorecase
    set incsearch
    set mouse=
    set nocompatible
    set nofoldenable
    set nu
    set pastetoggle=<F10>
    set ruler
    set shiftround
    set shortmess+=a
    set smartcase
    set smartindent
    set smarttab
    set sw=4
    set ts=4
    set sts=4
    set vb t_vb=
    set modeline
    set tags+=.ctags.tags

"
" Basic editor bindings
"
    let mapleader = ","

    nmap <Leader>bq :qa<cr>
    nmap <Leader>bd :bd<cr>
    nmap <silent> <Leader>cs :let @/ = ""<cr>

    nmap <c-p> :bp<cr>
    nmap <c-n> :bn<cr>

    nmap <c-h> <c-w>h
    nmap <c-l> <c-w>l
    nmap <c-j> <c-w>j
    nmap <c-k> <c-w>k
    nmap <c-q> <c-w>q

    map <silent> <Leader>wb :%s:\v\s+$::<cr>

"
" Pathogen
"
    runtime bundle/vim-pathogen/autoload/pathogen.vim
    execute pathogen#infect()

"
" silver searcher
"
    nnoremap <Leader>ag :Ag <cword><cr>

"
" format xml
"
    map <silent> <Leader>xf !xmllint --format -<cr>

"
" instant-markdown
"
    let g:instant_markdown_autostart = 0
    map <silent> <Leader>mp :InstantMarkdownPreview<cr>

"
" CtrlP
"
    let g:ctrlp_map = ''
    let g:ctrlp_match_window_reversed = 0
    " let g:ctrlp_working_path_mode = 'w'
    let g:ctrlp_by_filename = 0
    let g:ctrlp_user_command = {
      \ 'types': {
        \ 1: [
        \     '.git',
        \     'cd %s && git ls-files . --cached --exclude-standard --others'
        \    ],
        \ 2: ['.hg', 'hg --cwd %s locate -I .'],
        \ 3: [
        \     '.svn',
        \     expand('<sfile>:p:h').'/tools/ctrlp_svn_user_command %s'
        \    ],
      \ },
      \ 'fallback':
      \     expand('<sfile>:p:h').'/tools/ctrlp_fallback_user_command %s'
    \ }
    nnoremap <Leader>bf :CtrlP<cr>
    nnoremap <Leader>bb :CtrlPBuffer<cr>
    nnoremap <Leader>bt :CtrlPTag<cr>

"
" Syntastic
"
    let g:syntastic_always_populate_loc_list = 1
    let g:syntastic_auto_loc_list = 0
    let g:syntastic_loc_list_height = 10
    let g:syntastic_check_on_wq = 0

    let g:syntastic_java_checkers=['javac']
    let g:syntastic_java_javac_config_file_enabled = 1
    let g:syntastic_java_javac_sort = 1

    let g:syntastic_perl_checkers=['perl']
    let g:syntastic_enable_perl_checker = 1

    map <Leader>lo :lopen<cr>
    map <Leader>lc :lclose<cr>

    map <Leader>lf :lfirst<cr>
    map <Leader>ll :llast<cr>

    map [A         :lprev<cr>
    map [B         :lnext<cr>

    map <Leader>mm :w<cr> :SyntasticCheck<cr>
    map <Leader>sr :SyntasticReset<cr>
    map <Leader>si :SyntasticInfo<cr>
    map <Leader>st :SyntasticToggleMode<cr>

"
" NERDTree
"
    nnoremap <silent> <Leader>tr :NERDTreeToggle<cr>
    nnoremap <silent> <Leader>tf :NERDTreeFind<cr>

    let NERDTreeQuitOnOpen = 1

"
" EasyAlign
"
    vmap <cr>       <Plug>(EasyAlign)
    nmap <Leader>ea <Plug>(EasyAlign)

"
" UltiSnips
"
    let g:UltiSnipsExpandTrigger="<tab>"
    let g:UltiSnipsListSnippets="<c-s>"
    let g:UltiSnipsJumpForwardTrigger="<tab>"
    let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

"
" Tagbar
"
    let g:tagbar_width = 45
    let g:tagbar_zoomwidth = 90
    let g:tagbar_autopreview = 0
    let g:tagbar_show_linenumbers = 1
    let g:tagbar_indent = 0
    let g:tagbar_compact = 1
    let g:tagbar_autofocus = 1
    let g:tagbar_autoclose = 1
    nnoremap <Leader>to :TagbarToggle<cr>

    nnoremap <Leader>ta :ta
    nnoremap <Leader>tn :tnext<cr>
    nnoremap <Leader>tp :tprevious<cr>

"
" Git Gutter
"
    highlight SignColumn term=standout ctermfg=14 ctermbg=234 guifg=Cyan guibg=Grey

    highlight GitGutterAdd          ctermfg=2   ctermbg=0 guifg=#009900 guibg=Black
    highlight GitGutterChange       ctermfg=3   ctermbg=0 guifg=#bbbb00 guibg=Black
    highlight GitGutterDelete       ctermfg=1   ctermbg=0 guifg=#ff2222 guibg=Black
    highlight GitGutterChangeDelete ctermfg=171 ctermbg=0 guifg=#ff2222 guibg=Black

    let g:gitgutter_sign_added = '++'
    let g:gitgutter_sign_modified = '~~'
    let g:gitgutter_sign_removed = '__'
    let g:gitgutter_sign_modified_removed = '≂≂'
    let g:gitgutter_max_signs = 1000

    nnoremap <silent> <Leader>gn :GitGutterNextHunk<cr>
    nnoremap <silent> <Leader>gp :GitGutterPrevHunk<cr>
    nnoremap <silent> <Leader>gr :GitGutterRevertHunk<cr>

"
" vim-fugitive
"
    nnoremap <silent> <Leader>gb :Gblame<cr>
    vnoremap <silent> <Leader>gb :Gblame<cr>

"
" Toggle tw
"
    nnoremap <silent> <Leader>tw :TwToggle<cr>
    command TwToggle call ToggleTextWidth()

    function ToggleTextWidth()
    if !exists("b:toggleTw") || !b:toggleTw
        let b:toggleTw=1
        let &tw=b:maxwidth
    else
        let b:toggleTw=0
        set tw=0
    endif

    echo "tw="&tw
    endfunction

"
" Toggle wr
"
    nnoremap <silent> <Leader>wr :WrToggle<cr>
    command WrToggle call ToggleWrap()

    function ToggleWrap()
    if !exists("b:toggleWr") || !b:toggleWr
        let b:toggleWr=1
        set nowrap
    else
        let b:toggleWr=0
        set wrap
    endif

    endfunction

"
" Toggle VeryMagic
"
    nnoremap <silent> <Leader>vm :VMagicToggle<cr>
    command VMagicToggle call ToggleVMagic()

    function ToggleVMagic()
    if !exists("b:toggleVmagic") || !b:toggleVmagic
        let b:toggleVmagic=1
        let g:VeryMagic=0
    else
        let b:toggleVmagic=0
        let g:VeryMagic=1
    endif

    let g:VeryMagic

    endfunction

"
" indentLine
"
    let g:indentLine_enabled    = 0
    let g:indentLine_color_term = 214
    let g:indentLine_char = '│'
    nnoremap <silent> <Leader>ir :IndentLinesToggle<cr>

"
" colorcolumn
"
    " set "no man's land" past max line width to black background
    hi ColorColumn ctermbg=232 guibg=#080808

    command -nargs=1 SetColorColumn call SetColorColumn(<f-args>)

    function SetColorColumn(maxwidth)
        let b:maxwidth=a:maxwidth
        let &colorcolumn=join(range(b:maxwidth+1,999),",")
    endfunction

"
" autocmds
"
    au BufEnter * call SetDefaultOptions()
    function SetDefaultOptions()
        set formatoptions-=o
        set formatoptions+=r
        call SetColorColumn(78)
    endfunction
