#
# /etc/bash.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

if [[ -d /etc/profile.d ]]
then
    for f in /etc/profile.d/*
    do
        . $f
    done
fi

[ -r /usr/share/bash-completion/bash_completion ] \
    && . /usr/share/bash-completion/bash_completion


set -o vi
stty -ixon

alias ls='ls --color=auto'
alias diff='colordiff -u'
