#
# /etc/bash.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

[ -r /usr/share/bash-completion/bash_completion ] \
    && . /usr/share/bash-completion/bash_completion


set -o vi
stty -ixon

alias ls='ls --color=auto'
alias diff='colordiff -u'
