
"
" Main editor settings
"
    set t_Co=256

    syntax on
    colorscheme wombat256mod

    filetype plugin indent on

    set nocompatible
    set autoindent
    set backspace=indent,eol,start
    set complete-=i
    set cursorline
    set expandtab
    set hidden
    set hls
    set ignorecase
    set incsearch
    set mouse=
    set nocompatible
    set nofoldenable
    set nu
    set pastetoggle=<F10>
    set ruler
    set shiftround
    set shortmess+=a
    set smartcase
    set smartindent
    set smarttab
    set sw=4
    set ts=4
    set sts=4
    set vb t_vb=
    set modeline

"
" Main editor bindings
"
    let mapleader = ","

    nmap <Leader>bq :qa<cr>
    nmap <Leader>bd :bd<cr>
    nmap <silent> <Leader>cs :let @/ = ""<cr>

    nmap <c-p> :bp<cr>
    nmap <c-n> :bn<cr>

    nmap <c-h> <c-w>h
    nmap <c-l> <c-w>l
    nmap <c-j> <c-w>j
    nmap <c-k> <c-w>k
    nmap <c-q> <c-w>q

    map <silent> <Leader>wb :%s:\s\+$::<cr>
    map <silent> <Leader>mm :w<cr>:silent make<cr>:cope<cr>:redraw!<cr>

    map <Leader>co :cope<cr>

"
" Global variables
"
    let g:maxwidth=78

"
" Load plugins using pathogen
"
    runtime bundle/vim-pathogen/autoload/pathogen.vim
    execute pathogen#infect()

"
" Finally source all additional configurations
"
    let s:vimrcd=$HOME.'/.vimrc.d/'
    for s:i in split(globpath(s:vimrcd, '*.vim'), '\n')
        exec printf('source %s', s:i)
    endfor

