runtime bundle/vim-pathogen/autoload/pathogen.vim

set t_Co=256

syntax on
colorscheme wombat256mod

filetype plugin indent on

set backspace=indent,eol,start
set nocompatible
set nu
set expandtab
set autoindent
set smarttab
set sw=4
set ts=4
set hidden
set hls
set ignorecase
set smartcase
set ruler
set vb t_vb=

set pastetoggle=<F10>

nmap ,bq :qa<cr>
nmap ,bd :bd<cr>
nmap <silent> ,cs :let @/ = ""<cr>

nmap <c-p> :bp<cr>
nmap <c-n> :bn<cr>

nmap <c-h> <c-w>h
nmap <c-l> <c-w>l
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-q> <c-w>q

vmap ,aa :Align

map <silent> ,wb :%s:\s\+$::<cr>
map <silent> ,mm :w<cr>:silent make<cr>:cope<cr>:redraw!<cr>

set shortmess+=a
map ,co :cope<cr>

" Git Gutter
    highlight SignColumn term=standout ctermfg=14 ctermbg=234 guifg=Cyan guibg=Grey

    highlight GitGutterAdd          ctermfg=2 ctermbg=0 guifg=#009900 guibg=Black
    highlight GitGutterChange       ctermfg=3 ctermbg=0 guifg=#bbbb00 guibg=Black
    highlight GitGutterDelete       ctermfg=1 ctermbg=0 guifg=#ff2222 guibg=Black
    highlight GitGutterChangeDelete ctermfg=171 ctermbg=0 guifg=#ff2222 guibg=Black

    let g:gitgutter_sign_added = '++'
    let g:gitgutter_sign_modified = '~~'
    let g:gitgutter_sign_removed = '__'
    let g:gitgutter_sign_modified_removed = '≂≂'
