alias grep='grep --color=always'
alias gits='git status -s'
alias ls='ls --color=always'
alias cpanm='cpanm -v'
alias tree='tree -aC -I .git'
alias diff='colordiff -u'
alias view='vim -R'
alias gview='gvim -R'
alias vi='vim -v -u NONE'
