alias grep='grep --color=auto'
alias gits='git status -s'
alias ls='ls --color=auto'
alias cpanm='cpanm -v'
alias tree='tree -AC'
alias diff='colordiff -u'
alias view='vim -R'
alias gview='gvim -R'
alias vi='vim -v -u NONE'
