#!/usr/bin/env perl

use strict;
use warnings;
use v5.10;

my $dir = $ARGV[0];

my $ignore_config = "$ENV{HOME}/.ctrlp_ignore";
my @ignore_patterns;

if ( -f $ignore_config ) {
    open my $ignore_fh, '<', $ignore_config;

    for my $ignore (<$ignore_fh>) {
        chomp $ignore;
        push @ignore_patterns, $ignore;
    }
}

my $grep_arg =  join '',
                map { " -e '$_'" }
                grep { !/^\s*#/  }
                @ignore_patterns;

my $filter_cmd = qq(find -L $dir -type f);
$filter_cmd   .= qq(| egrep -v $grep_arg) if $grep_arg;

system($filter_cmd);
